name: Deployment Workflow
on:
  push:
    branches: [main]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Testing SSH
        uses: appleboy/ssh-action@master
        with:
          host: 128.199.72.149
          username: root
          key: ${{ secrets.SSH_SECRET }}
          port: 22
          script: |
            cd Ostendo-Ticketing
            git pull
            npm i
            pm2 reload server.js
            cd client
            npm i
            npm run build
